### ISSUE TITLE
Requirements version Missmatch on documentation

### ISSUE THREAD

**Issue by ggari-robotnik** [fluidos-project/fluidos-modelbased-metaorchestrator#31]
On [README.md](https://github.com/fluidos-project/node/blob/main/README.md)

The requirements sections I think that there is version missmatch here:

Kubernetes version -> 28.1.0 Could be 1.28.0?
kubectl plugin -> 0.0.2  is not released yet, This should be 0.0.1?

Can you check this minor things?

**Comment by andreacv98** [comment]
I think would be useful to add in the requirements **kopf** software along with a link to how to install it, since for the development installation is something necessary.

**Comment by stefano81** [comment]
Fixed in #36
